<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 17.04.2018
 * Time: 16:55
 */

namespace AppBundle\Service\Form;


use AppBundle\Entity\Category;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CategoryType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
{
//        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
    $builder
        ->add('nazwaKat')
        ->add('save', SubmitType::class);
}
public function configureOptions(OptionsResolver $resolver)
{
//        parent::configureOptions($resolver); // TODO: Change the autogenerated stub

    $resolver->setDefaults(['data_class' => Category::class]);
}
}